### ISSUE TITLE
Move files to src/

### ISSUE THREAD

**Issue by szepeviktor** [stellarwp/schema#25]
src/Schema/ 👉🏻 src/
After #20 

"src/Schema/" is PSR-0!

**Comment by borkweb** [comment]
The `/src/Schema/` pattern is purposeful so that we have `/src/functions/`, `/src/views/`, `/src/admin-views/`, `/src/deprecated/`, etc as sibling directories to the PHP class directories.

A worthy suggestion, but one that we won't be adopting as we like to have a separation between those concerns listed above while keeping all of the source code under a single tree. (i.e. we are not interested in `/admin-views` over `/src/admin-views/`.
